# Config file for automatic testing at travis-ci.org

language: python

python:
  - "3.4"
  - "3.3"
  - "2.7"
  - "pypy"

# command to install dependencies, e.g. pip install -r requirements.txt --use-mirrors
install:
  - sudo apt-get install libxml2-dev libxslt-dev python-dev lib32z1-dev
  - pip install -r requirements.txt

# command to run tests, e.g. python setup.py test
script:
    - pip install -r test_requirements.txt
    - cd tests/ && nosetests -v --with-xcoverage --cover-package=scrapple

after_success:
    - coveralls
